### ISSUE TITLE
where to find the data `conflict` in `21-conflict-nba_rivalries.R`?

### ISSUE THREAD

**Issue by liamxg** [gkaramanis/30DayMapChallenge#1]
Dear @gkaramanis,

Could I know where to find the data `conflict` in `21-conflict-nba_rivalries.R`?
Thanks.

Best,
Liam

**Comment by gkaramanis** [comment]
I got the rivalries from [this Wikipedia list](https://en.wikipedia.org/wiki/List_of_NBA_rivalries), the data frame with the coordinates etc. for the map is created in the script

**Comment by liamxg** [comment]
Dear @gkaramanis ,

the data `conflict` is from here:

```
 geom_curve(data = conflict %>% 
             mutate(conference_type = factor(conference_type, 
                    levels = c("Western", "Interconference", "Eastern"))), 
             aes(x = x, xend = xend, y = y, yend = yend, color = conference_type), 
             linewidth = 1.5, alpha = 0.5)
```

Could you attach the data.

Thanks.

Best,
Liam

**Comment by gkaramanis** [comment]
It seems that I somehow delete the part of the code that created conflict. It should be back now!

**Comment by liamxg** [comment]
Dear @gkaramanis ,

That's really cool! 
Thanks.

Best,
Liam
